using System;
using System.Collections.Generic;

using System.Text;
using Antlr.Runtime;
using Antlr.Runtime.Tree;

// This class is intended to put extension methods in scope in
// the ParserExtensions class which is generated by Antlr. These
// extensions provide backwards compatability with the java target
// of the MetraScript.g grammar so we can easily switch between using
// AntlrWorks and our C# program.
namespace ParserExensionsNameSpace
{
    static class ParserExtensions
    {
        public static int getLine(this IToken t)
        {
            return t.Line;
        }
        public static int getCharPositionInLine(this IToken t)
        {
            return t.CharPositionInLine;
        }

    }
}
