//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by mvm.exe.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace MetraTech.DomainModel.MvmEntityTypes
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [System.SerializableAttribute()]
    [System.Runtime.Serialization.DataContractAttribute()]

    [KnownType(typeof(my_tollfree_reservationless_bridgerate))]
    [KnownType(typeof(param_table))]
    public class MvmBaseObject : MetraTech.DomainModel.BaseTypes.BaseObject
    {
        // nothing in here. We just needed to decorate BaseObject
    }
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.SerializableAttribute()]
    public class my_tollfree_reservationless_bridgerate : MetraTech.DomainModel.MvmEntityTypes.MvmBaseObject
    {

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isStart_dateDirty = false;

        private System.Nullable<System.DateTime> start_date;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsStart_dateDirty
        {
            get
            {
                return this.isStart_dateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for start_date", MsixType = "System.DateTime")]
        public System.Nullable<System.DateTime> Start_date
        {
            get
            {
                return this.start_date;
            }
            set
            {
                this.start_date = value;
                this.isStart_dateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.start_date", DefaultValue = "start_date", MTLocalizationId = "metratech.com/my_tollfree_reservationless_bridgerate/start_date", Extension = "MVM", LocaleSpace = "metratech.com/my_tollfree_reservationless_bridgerate", LocalizationFiles = new string[] {
                  
      "metratech.com_my_tollfree_reservationless_bridgerate_de.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_fr.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_it.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_jp.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_us.xml"})]
        public string Start_dateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.start_date");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isEnd_dateDirty = false;

        private System.Nullable<System.DateTime> end_date;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsEnd_dateDirty
        {
            get
            {
                return this.isEnd_dateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for end_date", MsixType = "System.DateTime")]
        public System.Nullable<System.DateTime> End_date
        {
            get
            {
                return this.end_date;
            }
            set
            {
                this.end_date = value;
                this.isEnd_dateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.end_date", DefaultValue = "end_date", MTLocalizationId = "metratech.com/my_tollfree_reservationless_bridgerate/end_date", Extension = "MVM", LocaleSpace = "metratech.com/my_tollfree_reservationless_bridgerate", LocalizationFiles = new string[] {
                  
      "metratech.com_my_tollfree_reservationless_bridgerate_de.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_fr.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_it.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_jp.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_us.xml"})]
        public string End_dateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.end_date");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isId_accDirty = false;

        private System.Nullable<int> id_acc;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsId_accDirty
        {
            get
            {
                return this.isId_accDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for id_acc", MsixType = "int")]
        public System.Nullable<int> Id_acc
        {
            get
            {
                return this.id_acc;
            }
            set
            {
                this.id_acc = value;
                this.isId_accDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.id_acc", DefaultValue = "id_acc", MTLocalizationId = "metratech.com/my_tollfree_reservationless_bridgerate/id_acc", Extension = "MVM", LocaleSpace = "metratech.com/my_tollfree_reservationless_bridgerate", LocalizationFiles = new string[] {
                  
      "metratech.com_my_tollfree_reservationless_bridgerate_de.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_fr.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_it.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_jp.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_us.xml"})]
        public string Id_accDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.id_acc");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isToll_free_reservationless_bridgerateDirty = false;

        private System.Nullable<decimal> toll_free_reservationless_bridgerate;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsToll_free_reservationless_bridgerateDirty
        {
            get
            {
                return this.isToll_free_reservationless_bridgerateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for toll_free_reservationless_bridgerate", MsixType = "decimal")]
        public System.Nullable<decimal> Toll_free_reservationless_bridgerate
        {
            get
            {
                return this.toll_free_reservationless_bridgerate;
            }
            set
            {
                this.toll_free_reservationless_bridgerate = value;
                this.isToll_free_reservationless_bridgerateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.toll_free_reservationless_bridgerate", DefaultValue = "toll_free_reservationless_bridgerate", MTLocalizationId = "metratech.com/my_tollfree_reservationless_bridgerate/toll_free_reservationless_bridgerate", Extension = "MVM", LocaleSpace = "metratech.com/my_tollfree_reservationless_bridgerate", LocalizationFiles = new string[] {
                  
      "metratech.com_my_tollfree_reservationless_bridgerate_de.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_fr.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_it.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_jp.xml",
      "metratech.com_my_tollfree_reservationless_bridgerate_us.xml"})]
        public string Toll_free_reservationless_bridgerateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.my_tollfree_reservationless_bridgerate.toll_free_reservationless_bridgerate");
            }
        }

    } //end class

    [System.Runtime.Serialization.DataContractAttribute()]
    [System.SerializableAttribute()]
    public class param_table : MetraTech.DomainModel.MvmEntityTypes.MvmBaseObject
    {

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isStart_dateDirty = false;

        private System.Nullable<System.DateTime> start_date;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsStart_dateDirty
        {
            get
            {
                return this.isStart_dateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for start_date", MsixType = "System.DateTime")]
        public System.Nullable<System.DateTime> Start_date
        {
            get
            {
                return this.start_date;
            }
            set
            {
                this.start_date = value;
                this.isStart_dateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.param_table.start_date", DefaultValue = "start_date", MTLocalizationId = "metratech.com/param_table/start_date", Extension = "MVM", LocaleSpace = "metratech.com/param_table", LocalizationFiles = new string[] {
                  
      "metratech.com_param_table_de.xml",
      "metratech.com_param_table_fr.xml",
      "metratech.com_param_table_it.xml",
      "metratech.com_param_table_jp.xml",
      "metratech.com_param_table_us.xml"})]
        public string Start_dateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.param_table.start_date");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isEnd_dateDirty = false;

        private System.Nullable<System.DateTime> end_date;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsEnd_dateDirty
        {
            get
            {
                return this.isEnd_dateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for end_date", MsixType = "System.DateTime")]
        public System.Nullable<System.DateTime> End_date
        {
            get
            {
                return this.end_date;
            }
            set
            {
                this.end_date = value;
                this.isEnd_dateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.param_table.end_date", DefaultValue = "end_date", MTLocalizationId = "metratech.com/param_table/end_date", Extension = "MVM", LocaleSpace = "metratech.com/param_table", LocalizationFiles = new string[] {
                  
      "metratech.com_param_table_de.xml",
      "metratech.com_param_table_fr.xml",
      "metratech.com_param_table_it.xml",
      "metratech.com_param_table_jp.xml",
      "metratech.com_param_table_us.xml"})]
        public string End_dateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.param_table.end_date");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isId_accDirty = false;

        private System.Nullable<int> id_acc;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsId_accDirty
        {
            get
            {
                return this.isId_accDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for id_acc", MsixType = "int")]
        public System.Nullable<int> Id_acc
        {
            get
            {
                return this.id_acc;
            }
            set
            {
                this.id_acc = value;
                this.isId_accDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.param_table.id_acc", DefaultValue = "id_acc", MTLocalizationId = "metratech.com/param_table/id_acc", Extension = "MVM", LocaleSpace = "metratech.com/param_table", LocalizationFiles = new string[] {
                  
      "metratech.com_param_table_de.xml",
      "metratech.com_param_table_fr.xml",
      "metratech.com_param_table_it.xml",
      "metratech.com_param_table_jp.xml",
      "metratech.com_param_table_us.xml"})]
        public string Id_accDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.param_table.id_acc");
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        private bool isToll_free_reservationless_bridgerateDirty = false;

        private System.Nullable<decimal> toll_free_reservationless_bridgerate;

        [System.Web.Script.Serialization.ScriptIgnoreAttribute()]
        public bool IsToll_free_reservationless_bridgerateDirty
        {
            get
            {
                return this.isToll_free_reservationless_bridgerateDirty;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        [MetraTech.DomainModel.Common.MTDataMemberAttribute(IsRequired = false, Length = 100, Description = "description for toll_free_reservationless_bridgerate", MsixType = "decimal")]
        public System.Nullable<decimal> Toll_free_reservationless_bridgerate
        {
            get
            {
                return this.toll_free_reservationless_bridgerate;
            }
            set
            {
                this.toll_free_reservationless_bridgerate = value;
                this.isToll_free_reservationless_bridgerateDirty = true;
            }
        }

        [MetraTech.DomainModel.Common.MTPropertyLocalizationAttribute(ResourceId = "MetraTech.DomainModel.MvmEntityTypes.param_table.toll_free_reservationless_bridgerate", DefaultValue = "toll_free_reservationless_bridgerate", MTLocalizationId = "metratech.com/param_table/toll_free_reservationless_bridgerate", Extension = "MVM", LocaleSpace = "metratech.com/param_table", LocalizationFiles = new string[] {
                  
      "metratech.com_param_table_de.xml",
      "metratech.com_param_table_fr.xml",
      "metratech.com_param_table_it.xml",
      "metratech.com_param_table_jp.xml",
      "metratech.com_param_table_us.xml"})]
        public string Toll_free_reservationless_bridgerateDisplayName
        {
            get
            {
                return ResourceManager.GetString("MetraTech.DomainModel.MvmEntityTypes.param_table.toll_free_reservationless_bridgerate");
            }
        }

    } //end class

    public struct MvmEntityInfo
    {
        public string EntityName;
        public string ClassName;
        public string AssemblyName;
        public MvmEntityInfo(string EntityName, string ClassName, string AssemblyName)
        {
            this.EntityName = EntityName;
            this.ClassName = ClassName;
            this.AssemblyName = AssemblyName;
        }
    }
    [System.Runtime.Serialization.DataContractAttribute()]
    [System.SerializableAttribute()]
    public class MvmEntityMenu : MetraTech.DomainModel.MvmEntityTypes.MvmBaseObject
    {
        private static List<MvmEntityInfo>
          mvmEntityInfoList = new List<MvmEntityInfo>
            ();
        static MvmEntityMenu()
        {
            mvmEntityInfoList.Add(new MvmEntityInfo("my_tollfree_reservationless_bridgerate", "my_tollfree_reservationless_bridgerate", "xxxx.dll"));

            mvmEntityInfoList.Add(new MvmEntityInfo("param_table", "param_table", "xxxx.dll"));

        }
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = false, EmitDefaultValue = false)]
        public List<MvmEntityInfo> MvmEntityInfoList
        {
            get
            {
                return mvmEntityInfoList;
            }
        }
    }// end class
}//end namespace